#:kivy 2.1.0
<AButton@Button>:
    font_size: 32
    color:0,0,0,1
    size:150,50
    background_normal:""
    background_down:"bt-down.png"
    background_color:0.88,0.88,0.88,1
    on_press:
        color: 1,0,0,1

<MyWidget>:
    font_size:32
    color:0,0,0,1
    size:150,150
    background_color:0.88,0.88,0.88,1
    AButton:
        text:"Settings"
        pos:root.x,550
        on_release:
            
        
    AButton:
        text:"Filters"
        pos:650,550
        
